---
on:
  workflow_dispatch:
name: Create Release
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3.3.0
      - run: git archive --format zip -o release.zip HEAD
      - uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
